# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Compiles godot project
    - name: Godot Export
      uses: firebelley/godot-export@v2.1.0
      with:
        # The download url of the 64 bit Linux Headless Godot executable.
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
        # The url of the export templates corresponding to the Godot executable version.
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
        # The relative path containing the "project.godot" file.
        relative_project_path: $GITHUB_WORKSPACE
        # If exports should be archived.
        archive_export_output: true
        # If exports that result in single files should be archived.
        #archive_single_release_output: # optional, default is true
        # The version which new releases start at.
        #base_version: # optional, default is 0.0.1
        # If releases should be automatically created.
        #create_release: # optional, default is true
        # If release notes should be automatically generated based on commit history.
        #generate_release_notes: # optional
        # If provided, exports will be moved to this directory relative to the root of the Git repository.
        #relative_export_path: # optional, default is 
        # If Windows executable icons should be updated with the preset's .ico file.
        #update_windows_icons: # optional
